In [1]:
import numpy as np
import os


In [2]:
###Load All data from the path
def get_all_npy(path : str) -> dict:
    files = dict()
    for root, dir , _files in os.walk(path):
        for file in _files:
            if file.endswith(".npy"):
                name = file.split(".npy")[0]
                files[name] = os.path.join(root, file) 
    return files
###It takes the list of data and then zeros out the required dates
def elminate_date(npy_files : list,
                 list_dates : list) -> np.array:
    files_result = {}
    for name , npy_file in npy_files.items():
        data = np.load(npy_file)
        for date in list_dates:
            matrix_date = data[date]
            data[date] = np.zeros(matrix_date.shape)
        files_result[name] = data
    return files_result


In [3]:
list_dates = [14, 15, 16]
os.makedirs("/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA_zero", exist_ok=True)
npy_files = get_all_npy("/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA")
x = elminate_date(npy_files, list_dates)
print("npy_files: ",npy_files)
for file in x:
    path = f"/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA_zero/{file}.npy"
    np.save(path, x[file])

data1 = np.load("/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA_zero/1.npy")
print("data1.shape: ",data1.shape)
print("data1[15]: ",data1[15])

npy_files:  {'5': '/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA/5.npy', '4': '/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA/4.npy', '3': '/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA/3.npy', '1': '/home/mhbokaei/shakouri/test/RStest/dataset_folder/DATA/1.npy'}
data1.shape:  (24, 10, 1053)
data1[15]:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
